
var mockup = {
    "nodes":[
        {
            "name":"Walls", 
            "category":"foo", 
            "stored": 20
            "children":[
                {"name": "wall 1", "category", "stored":10},
                {"name": "wall 2", "category", "stored":10}
            ]
        },
    
    ],
    "parentLinks":[
        {"source":0,"target":1,"value":20},
        {"source":1,"target":2,"value":124.729}
    ]    
    "childLinks":[
        {"source":[0,0],"target":[1,1],"value":10},
        {"source":[0,0],"target":[1,0],"value":10}
    ]
}



var dObj = {
    "nodes":[
        {"name":"Agricultural 'waste'", "category":"foo", "wval": 20},
        {"name":"Bio-conversion", "category":"bar", "wval": 100},
        {"name":"Liquid", "category":"qux", "wval": 10},
        {"name":"Losses", "category":"baz", "wval": 10},
        {"name":"Solid", "category":"baz", "wval": 10},
        {"name":"Gas", "category":"baz", "wval": 10},
        {"name":"Biofuel imports", "category":"baz", "wval": 10},
        {"name":"Biomass imports", "category":"baz", "wval": 10},
        {"name":"Coal imports", "category":"baz", "wval": 10},
        {"name":"Coal", "category":"baz", "wval": 10},
        {"name":"Coal reserves", "category":"baz", "wval": 10},
        {"name":"District heating", "category":"baz", "wval": 10},
        {"name":"Industry", "category":"baz", "wval": 10},
        {"name":"Heating and cooling - commercial", "category":"baz", "wval": 10},
        {"name":"Heating and cooling - homes", "category":"baz", "wval": 10},
        {"name":"Electricity grid", "category":"baz", "wval": 10},
        {"name":"Over generation / exports", "category":"baz", "wval": 10},
        {"name":"H2 conversion", "category":"baz", "wval": 10},
        {"name":"Road transport", "category":"baz", "wval": 10},
        {"name":"Agriculture", "category":"baz", "wval": 10},
        {"name":"Rail transport", "category":"baz", "wval": 10},
        {"name":"Lighting & appliances - commercial", "category":"baz", "wval": 10},
        {"name":"Lighting & appliances - homes", "category":"baz", "wval": 10},
        {"name":"Gas imports", "category":"baz", "wval": 10},
        {"name":"Ngas", "category":"baz", "wval": 10},
        {"name":"Gas reserves", "category":"baz", "wval": 10},
        {"name":"Thermal generation", "category":"baz", "wval": 10},
        {"name":"Geothermal", "category":"baz", "wval": 10},
        {"name":"H2", "category":"baz", "wval": 10},
        {"name":"Hydro", "category":"baz", "wval": 10},
        {"name":"International shipping", "category":"baz", "wval": 10},
        {"name":"Domestic aviation", "category":"baz", "wval": 10},
        {"name":"International aviation", "category":"baz", "wval": 10},
        {"name":"National navigation", "category":"baz", "wval": 10},
        {"name":"Marine algae", "category":"baz", "wval": 10},
        {"name":"Nuclear", "category":"baz", "wval": 10},
        {"name":"Oil imports", "category":"baz", "wval": 10},
        {"name":"Oil", "category":"baz", "wval": 10},
        {"name":"Oil reserves", "category":"baz", "wval": 10},
        {"name":"Other waste", "category":"baz", "wval": 10},
        {"name":"Pumped heat", "category":"baz", "wval": 10},
        {"name":"Solar PV", "category":"baz", "wval": 10},
        {"name":"Solar Thermal", "category":"baz", "wval": 10},
        {"name":"Solar", "category":"baz", "wval": 10},
        {"name":"Tidal", "category":"baz", "wval": 10},
        {"name":"UK land based bioenergy", "category":"baz", "wval": 10},
        {"name":"Wave", "category":"baz", "wval": 10},
        {"name":"Wind", "category":"baz", "wval": 10}
    ],
    "links":[
        {"source":0,"target":1,"value":124.729},
        {"source":1,"target":2,"value":0.597},
        {"source":1,"target":3,"value":26.862},
        {"source":1,"target":4,"value":280.322},
        {"source":1,"target":5,"value":81.144},
        {"source":6,"target":2,"value":35},
        {"source":7,"target":4,"value":35},
        {"source":8,"target":9,"value":11.606},
        {"source":10,"target":9,"value":63.965},
        {"source":9,"target":4,"value":75.571},
        {"source":11,"target":12,"value":10.639},
        {"source":11,"target":13,"value":22.505},
        {"source":11,"target":14,"value":46.184},
        {"source":15,"target":16,"value":104.453},
        {"source":15,"target":14,"value":113.726},
        {"source":15,"target":17,"value":27.14},
        {"source":15,"target":12,"value":342.165},
        {"source":15,"target":18,"value":37.797},
        {"source":15,"target":19,"value":4.412},
        {"source":15,"target":13,"value":40.858},
        {"source":15,"target":3,"value":56.691},
        {"source":15,"target":20,"value":7.863},
        {"source":15,"target":21,"value":90.008},
        {"source":15,"target":22,"value":93.494},
        {"source":23,"target":24,"value":40.719},
        {"source":25,"target":24,"value":82.233},
        {"source":5,"target":13,"value":0.129},
        {"source":5,"target":3,"value":1.401},
        {"source":5,"target":26,"value":151.891},
        {"source":5,"target":19,"value":2.096},
        {"source":5,"target":12,"value":48.58},
        {"source":27,"target":15,"value":7.013},
        {"source":17,"target":28,"value":20.897},
        {"source":17,"target":3,"value":6.242},
        {"source":28,"target":18,"value":20.897},
        {"source":29,"target":15,"value":6.995},
        {"source":2,"target":12,"value":121.066},
        {"source":2,"target":30,"value":128.69},
        {"source":2,"target":18,"value":135.835},
        {"source":2,"target":31,"value":14.458},
        {"source":2,"target":32,"value":206.267},
        {"source":2,"target":19,"value":3.64},
        {"source":2,"target":33,"value":33.218},
        {"source":2,"target":20,"value":4.413},
        {"source":34,"target":1,"value":4.375},
        {"source":24,"target":5,"value":122.952},
        {"source":35,"target":26,"value":839.978},
        {"source":36,"target":37,"value":504.287},
        {"source":38,"target":37,"value":107.703},
        {"source":37,"target":2,"value":611.99},
        {"source":39,"target":4,"value":56.587},
        {"source":39,"target":1,"value":77.81},
        {"source":40,"target":14,"value":193.026},
        {"source":40,"target":13,"value":70.672},
        {"source":41,"target":15,"value":59.901},
        {"source":42,"target":14,"value":19.263},
        {"source":43,"target":42,"value":19.263},
        {"source":43,"target":41,"value":59.901},
        {"source":4,"target":19,"value":0.882},
        {"source":4,"target":26,"value":400.12},
        {"source":4,"target":12,"value":46.477},
        {"source":26,"target":15,"value":525.531},
        {"source":26,"target":3,"value":787.129},
        {"source":26,"target":11,"value":79.329},
        {"source":44,"target":15,"value":9.452},
        {"source":45,"target":1,"value":182.01},
        {"source":46,"target":15,"value":19.013},
        {"source":47,"target":15,"value":289.366}
    ]
};
